name: github pages

on:
  push

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.58.3'

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      if: github.ref == 'refs/heads/development'
      uses: peaceiris/actions-gh-pages@v3.6.4
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
